import esbuild from "esbuild";
import process from "process";
import { cpSync } from "node:fs";
import { join } from "node:path";
import { builtinModules } from "node:module";

const PLUGIN_FILES = ["main.js", "manifest.json", "styles.css"];

function copyToVaultPlugin() {
	const dest = process.env.OBSIDIAN_PLUGIN_DIR;
	return {
		name: "copy-to-vault",
		setup(build) {
			build.onEnd((result) => {
				if (!dest || result.errors.length > 0) {
					return;
				}
				for (const file of PLUGIN_FILES) {
					cpSync(file, join(dest, file));
				}
				console.log(`Synced → ${dest}`);
			});
		},
	};
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyToVaultPlugin()],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
